version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Docker"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-patch"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
